version: "3"
services:
  db:
    build: ./mysql/
    container_name: basededonne
    ports:
      - 3306:3306
    networks:
      - backend
  api:
    build: ./node/
    container_name: nodeapi
    ports:
      - 8080:8080
    networks:
      - backend
      - frontend
  frontend:
    build: ./front/
    container_name: front
    ports:
      - 3000:80
    networks:
      - frontend
networks:
  backend:
  frontend:
